### ISSUE TITLE
Following the readme: No "targetPort" option specified or detected.

### ISSUE THREAD

**Issue by msevestre** [netlify-templates/kpop-stack#47]
I followed the step by step instructions (I believe) and I am getting the following error when running `netlify dev`

Rebuilding...
Done in 274ms.
◈ Netlify Dev ◈
◈ Injected build setting env var: SUPABASE_URL
◈ Injected build setting env var: SUPABASE_ANON_KEY
◈ Injected build setting env var: SESSION_SECRET
◈ Overriding command with setting derived from netlify.toml [dev] block:  remix watch
◈ No "targetPort" option specified or detected.
ERROR: "dev:remix" exited with 1.

What should I do to make this work?

Thanks

**Comment by msevestre** [comment]
Ok I needed to upgrade the CLI

**Comment by maxcell** [comment]
@msevestre Glad you were able to resolve it yourself! Definitely a difficult error message to have resolved it with! What version of the CLI were you using?

**Comment by msevestre** [comment]
@maxcell I think it was v3.x .. very old lol

**Comment by msevestre** [comment]
And it took me a lot of time until I figured this out. Maybe a min supported cli version check somewhere could be helpful. At any rate, this is working great now
