### ISSUE TITLE
Issue with creating user, cannot read properties of null

### ISSUE THREAD

**Issue by maxcell** [netlify-templates/kpop-stack#50]
I can't make it work too. What am I missing here?

node --version:  v18.1.0

Running: npm run dev

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/3877117/172062336-adf72662-a9b5-4c54-bea2-5198de6366c9.png">

Getting this issue when creating a user:
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/3877117/172062292-1f7ea910-2005-4ec2-800f-f9c6428943eb.png">

_Originally posted by @leofmoura in https://github.com/netlify-templates/kpop-stack/issues/49#issuecomment-1146851662_

**Comment by leofmoura** [comment]
Hi Maxcell. This is what I get when try to signup.
The user is created in supabase. But it doesn't look like it's completing the operation.
When trying to login I get a invalid user/pass.

![image](https://user-images.githubusercontent.com/3877117/172178095-8f2a5de5-d7db-4e81-b46a-0c9966fb4fe9.png)

![image](https://user-images.githubusercontent.com/3877117/172178144-a96a4c38-b8f8-497c-a8fa-53250cd9928f.png)


When trying from deployed netlify site, I can't make it work too, but error is different:

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/3877117/172179766-5bdeac21-262f-45d5-8f9e-a7a2336f3a25.png">

looks like I have wrong configuration, but all I did was set variables copying from supabase settings.

Thanks

**Comment by leofmoura** [comment]
Ok, that fixed my local env. I missed that, thanks.

About the netlify site:

I'm getting this error when creating an account:

{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "FetchError: invalid json response body at https://rktuocznllhvbarshwit.supabase.co/auth/v1/signup reason: Unexpected token M in JSON at position 0",
  "trace": [
    "Runtime.UnhandledPromiseRejection: FetchError: invalid json response body at https://rktuocznllhvbarshwit.supabase.co/auth/v1/signup reason: Unexpected token M in JSON at position 0",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:400:28)",
    "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)",
    "    at processPromiseRejections (internal/process/promises.js:245:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:96:32)"
  ]
}

**Comment by leofmoura** [comment]
Yes, it fixed. I had a caching issue, but as soon I've re-deployed everything, it worked fine.
Nice to have you here!

**Comment by maxcell** [comment]
Glad it is all working. Thank you so much for opening the report and working with me on this! Keep us posted on what's next for ya! 😄
