### ISSUE TITLE
npx create-remix --template netlify-templates/kpop-stack is not working

### ISSUE THREAD

**Issue by eclecticlly** [netlify-templates/kpop-stack#55]
Hi @tzmanics, 

I'm receiving this error: 

`🚨 The template could not be verified because you do are not authorized to access that repository. Please double check the access rights of the repo or consider passing a --token`

Why I need a token on a public repo? 
For sure I can use the **_Deploy to Netlify_** button, but it's just to understand...

**Comment by maxcell** [comment]
Howdy @eclecticlly! Thank you for this report! I actually believe this is a bug with the Remix CLI. I am gonna report it and add this issue over there. Thank you for finding this!

I think for now, feel free to use the Deploy to Netlify button until this can be resolved.

**Comment by eclecticlly** [comment]
Thanks @maxcell, I was quite sure really that was a problem from Remix side.
I will use this stack a lot in the future, so expect to hear from me from time to time.
I think we can close the issue.
