### ISSUE TITLE
How to setup RLS?

### ISSUE THREAD

**Issue by allanpope** [netlify-templates/kpop-stack#82]
I've enabled RLS on my two tables profiles and parks (parks is your notes table, just renamed) but I cannot get it working. When creating a park I get this. I've tried a bunch of different policies but always get the same error.
<img width="772" alt="Screen Shot 2022-08-28 at 4 42 27 pm" src="https://user-images.githubusercontent.com/2561365/187057891-4fa3a082-b94f-481f-a1c7-658b275bac4e.png">

Added these polices for parks. Im using `profile_id` as thats the auth id.
<img width="662" alt="Screen Shot 2022-08-28 at 4 35 00 pm" src="https://user-images.githubusercontent.com/2561365/187057858-ab3a552a-ca3b-4621-89f0-ce4c6cdb0163.png">

If I remove RLS and policies I can create/update/delete parks. So that codes fine.

I've tried logging the session **[here](https://github.com/netlify-templates/kpop-stack/blob/main/app/models/note.server.ts#L25)** and it returns `null`.

I also tried copying a curl command from the api docs and that also returned the same error. Im guessing this one failed as its missing the `user_id` that I added in my policy
`{"code":"42501","details":null,"hint":null,"message":"new row violates row-level security policy for table \"parks\""}`

**Comment by Aminkavoos** [comment]
> I've enabled RLS on my two tables profiles and parks (parks is your notes table, just renamed) but I cannot get it working. When creating a park I get this. I've tried a bunch of different policies but always get the same error.
> <img width="772" alt="Screen Shot 2022-08-28 at 4 42 27 pm" src="https://user-images.githubusercontent.com/2561365/187057891-4fa3a082-b94f-481f-a1c7-658b275bac4e.png">
> 
> Added these polices for parks. Im using `profile_id` as thats the auth id.
> <img width="662" alt="Screen Shot 2022-08-28 at 4 35 00 pm" src="https://user-images.githubusercontent.com/2561365/187057858-ab3a552a-ca3b-4621-89f0-ce4c6cdb0163.png">
> 
> 
> If I remove RLS and policies I can create/update/delete parks. So that codes fine.
> 
> I've tried logging the session **[here](https://github.com/netlify-templates/kpop-stack/blob/main/app/models/note.server.ts#L25)** and it returns `null`.
> 
> I also tried copying a curl command from the api docs and that also returned the same error. Im guessing this one failed as its missing the `user_id` that I added in my policy
> `{"code":"42501","details":null,"hint":null,"message":"new row violates row-level security policy for table \"parks\""}`

**Comment by maxcell** [comment]
Hmmm... we need to investigate this. I am not quite sure why it is giving you issues. For the interim, it might be best to remove the RLS.

**Comment by allanpope** [comment]
> Hmmm... we need to investigate this. I am not quite sure why it is giving you issues. For the interim, it might be best to remove the RLS.

Dug into it slightly and it seemed like it was passing through the token. Ended up using a different starter

**Comment by awconway** [comment]
I can not get RLS working on this template either. any suggestions?
