### ISSUE TITLE
Question: What build script should i tell netlify to use?

### ISSUE THREAD

**Issue by jkohlin** [netlify-templates/kpop-stack#98]
There are lot of npm scripts, but no documentation of the different ones. 
Which one should I add to the Netlify settings:
![CleanShot 2022-10-11 at 10 15 12@2x](https://user-images.githubusercontent.com/4112881/195036089-43cb7bd8-a9a2-4a44-b388-aa57eaa9132a.png)

**Comment by maxcell** [comment]
Howdy @jkohlin! In cloning this project you shouldn't need to manually update this build command line but you can find the build settings within the [`netlify.toml` file](https://github.com/netlify-templates/kpop-stack/blob/41519397c0933088f8f57f49dd65283cfd1887d7/netlify.toml#L2) where it configures the build setting to exactly what you have which is `npm run build`.

**Comment by jkohlin** [comment]
Thanks. I think it was due to reusing an old netlify site that was pointing to another repo.

**Comment by maxcell** [comment]
No worries at all! Thank you for asking all the same!
